working_dir: "/tmp/postgres-ci/builds/"
assets     : "/opt/postgres-ci/worker/assets"
loglevel   : "info" # info/warning/error
num_workers: auto # number or auto (defines the number of parallel build process)

debug:
  host: 127.0.0.1
  port: 8080

connect:
  host: "/var/run/postgresql"
  #host: 172.16.9.131
  port: 5432
  username: "postgres_ci"
  password: "iAmAdiscoDancer"
  database: "postgres_ci"

docker:
  endpoint: "unix:///var/run/docker.sock"
  tls_cert_path:
  auth:
    username:
    password:
    email:
    server_address:
