working_dir: "/tmp/postgres-ci/builds/"
assets: "/opt/postgres-ci/worker/assets"

debug:
  host: 10.211.55.6
  port: 8080

logger:
  level: "info" # info/warning/error
  logfile: "/var/log/postgres-ci/worker.log"

connect:
  host: "/var/run/postgresql"
  port: 5432
  username: "postgres_ci"
  password: "iAmAdiscoDancer"
  database: "postgres_ci"

docker:
  endpoint: "unix:///var/run/docker.sock"
  tls_cert_path:
  auth:
    username:
    password:
    email:
    server_address:
